---
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
version: '{build}'
shallow_clone: true

matrix:
  fast_finish: true

environment:
  HARNESS_BREAK: 1
  FCS_USE_TEST_RUN: 1
  WMLOPTS: '--passoption 3,-x'
  PERL_MM_USE_DEFAULT: 1
  matrix:
    - perl_type: cygwin64

install:
    - choco install ag
    - 'call .appveyor.cmd perl_setup'
    - '%perl% -V'
    - "%cpanm% -n Bit::Vector Class::XSAccessor File::Which Getopt::Long IO::All Image::Size Perl::Tidy Test::Code::TidyAll Term::ReadKey"
build: off
test_script:
    - 'mkdir build && cd build && %perl% ../src/wml_test/run_test.pl'
