---
version: '{build}'
shallow_clone: true
build: off

matrix:
  fast_finish: true

environment:
  HARNESS_BREAK: 1
  FCS_USE_TEST_RUN: 1
  WMLOPTS: '--passoption 3,-x'
  PERL_MM_USE_DEFAULT: 1
  matrix:
    - perl_type: cygwin
      ARCH: x86_64
      CYGWIN: 'C:\Cygwin64'
      CYGSH: 'C:\Cygwin64\bin\bash -e -l'
      CYGDRIVE: /cygdrive/c/cygwin64

install:
    - choco install ag
    - 'call .appveyor.cmd perl_setup'

test_script:
    - cmd: if [%perl_type%]==[cygwin] (
        %CYGSH% repo/.appveyor.sh) else (
        %perl% -V
        cpanm -n Bit::Vector Class::XSAccessor File::Which Getopt::Long IO::All Image::Size Perl::Tidy Test::Code::TidyAll Term::ReadKey
        cd build
        %perl% ..\src\wml_test\run_test.pl)
