---
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
install:
    - choco install ag
    # - choco install strawberryperl
    # - if not exist C:\libtap mkdir C:\libtap
    # - copy c:\Python35-x64\python.exe c:\Python35-x64\python3.exe
    # - SET PATH=C:\Python35-x64;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    # - python3 -mpip install six
    # - perl -v
    # - copy C:\msys64\mingw64\bin\mingw32-make.exe C:\msys64\mingw64\bin\make.exe
    # - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    # - SET PERL5LIB=C:/_P5/lib/perl5
    # - SET PERL_LOCAL_LIB_ROOT=C:/_P5
    # - SET PERL_MB_OPT=--install_base C:/_P5
    # - SET PERL_MM_OPT=INSTALL_BASE=C:/_P5
    # - perl -v
    # - cpanm --notest Bit::Vector Class::XSAccessor File::Which GD Getopt::Long IO::All Image::Size Perl::Tidy Test::Code::TidyAll Term::ReadKey
    # - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - echo %PATH%
    - C:\cygwin64\setup-x86_64.exe -qgnNdO -l C:\cygwin64\var\cache\setup -R c:\cygwin64 -s http://cygwin.mirror.constant.com -P cmake -P gcc -P g++ -P glibc-devel -P libcrypt-devel -P libncurses-devel -P libgd-devel -P perl -P perl-CPAN -P perl-devel
    - c:\cygwin64\bin\bash -e -l -c "export PERL_MM_USE_DEFAULT=1; cpan -i App::cpanminus; eval ""$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"" ; cpan -T -i Bit::Vector Class::XSAccessor File::Which GD Getopt::Long IO::All Image::Size Perl::Tidy Test::Code::TidyAll Term::ReadKey || true"
build: off
test_script:
    - set HARNESS_BREAK=1
    - set FCS_USE_TEST_RUN=1
    - xcopy /i /q /s c:\Projects\website-meta-language c:\cygwin64\home\appveyor\website-meta-language && c:\cygwin64\bin\bash -e -l -c "export PERL_MM_USE_DEFAULT=1; eval ""$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"" ; ls ; cd website-meta-language/ ; mkdir build; cd build; perl ../src/wml_test/run_test.pl"
shallow_clone: true
