os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y asciidoc build-essential cmake cpanminus dbtoepub docbook-defguide docbook-xsl docbook-xsl-ns fortune-mod hunspell inkscape myspell-en-gb libhunspell-dev libperl-dev optipng perl python3 python3-setuptools python3-pip valgrind wml xsltproc xz-utils yui-compressor zip
python:
    - "3.5"
script:
    - mkdir build
    - cd build
    - perl ../src/wml_test/run_test.pl
