os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential cmake cpanminus fortune-mod hunspell myspell-en-gb libhunspell-dev libperl-dev perl python3 python3-setuptools python3-pip valgrind xsltproc xz-utils zip
    - sudo cpanm IO::All
python:
    - "3.5"
script:
    - mkdir build
    - cd build
    - perl ../src/wml_test/run_test.pl
